version: "3.8"
volumes:
  src:
    driver_opts:
      type: none
      device: $PWD/server
      o: bind
  postgres-data:
    driver: local
services:
  db:
    image: postgres:16rc1-bookworm
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=trvl
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./docker/db/init:/docker-entrypoint-initdb.d
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    volumes:
      - src:/go/src/app
    ports:
      - 5000:5000
    environment:
      - ENV=dev
